services:
  mysql:
    image: mysql:8.0
    container_name: healthcare_mysql
    restart: unless-stopped

    environment:
      MYSQL_DATABASE: healthcare_analysis
      MYSQL_USER: healthcare_user
      MYSQL_PASSWORD: healthcare_password
      MYSQL_ROOT_PASSWORD: root_password

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
